# Missing Data and Meteors

Today we'll be working with fireball data. This exercise is less scaffolded than previous exercises, to prepare you for your final projects.

Fireballs are small asteroids that burn up as they enter into the atmosphere. You can get today's data from:
https://cneos.jpl.nasa.gov/fireballs/

Please download a csv file of the data.

Load up the data below. (Feel free to see how we did this in past assignments. If you have questions, call me over or ask a teammate for help!)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("cneos_fireball_data.csv")

Take a look at the data. What are the column headings? Is there any missing data?

In [13]:
data.head(30)

,Peak Brightness Date/Time (UT),Latitude (deg.),Longitude (deg.),Altitude (km),vx,vy,vz,Total Radiated Energy (J),Calculated Total Impact Energy (kt)
0,2025-09-13 22:24:59,38.1S,64.8W,25.1,-17.4,1.7,3.6,1.670000e+11,0.480
1,2025-09-10 11:00:57,14.8S,142.4W,37.0,NaN,NaN,NaN,2.800000e+10,0.098
2,2025-09-09 17:49:10,2.3S,39.5W,24.0,-3.6,20.4,0.0,1.530000e+11,0.440
3,2025-09-08 10:09:15,26.4N,42.2E,28.4,NaN,NaN,NaN,3.600000e+10,0.120
4,2025-08-19 14:08:48,30.9N,131.8E,27.5,14.7,-13.0,0.1,6.580000e+11,1.600
5,2025-07-11 01:48:33,6.6S,167.5W,28.0,13.4,1.8,-0.9,3.200000e+10,0.110
6,2025-06-26 16:24:57,33.4N,84.1W,32.6,NaN,NaN,NaN,1.700000e+11,0.480
7,2025-06-26 00:37:20,12.1N,103.6W,30.0,16.2,10.3,1.6,1.320000e+11,0.390
8,2025-06-21 20:55:14,61.3S,157.9E,56.3,NaN,NaN,NaN,3.000000e+10,0.100
9,2025-05-31 23:06:33,21.1N,98.8W,47.3,12.2,8.6,-9.7,3.860000e+11,1.000
10,2025-04-28 15:01:15,45.1S,67.3E,31.4,NaN,NaN,NaN,3.400000e+10,0.120
11,2025-04-21 09:27:34,29.1S,151.6E,41.0,NaN,NaN,NaN,2.300000e+10,0.082
12,2025-04-08 14:16:48,32.2S,10.4E,44.9,-20.4,9.7,-0.4,2.100000e+10,0.076
13,2025-03-29 08:12:43,49.3S,14.3E,21.6,-8.9,-5.2,6.8,5.900000e+10,0.190
14,2025-03-27 16:05:23,14.3N,111.5W,38.1,-7.3,19.8,-2.8,1.045000e+12,2.400
15,2025-03-24 05:51:43,70.4S,114.2E,21.5,-0.9,-24.8,13.4,4.900000e+10,0.160
16,2025-03-21 05:06:26,22.8S,123.5E,54.2,NaN,NaN,NaN,3.900000e+10,0.130
17,2025-03-18 17:48:32,1.5S,30.4W,27.0,-6.6,18.7,-3.1,1.100000e+11,0.330
18,2025-03-13 09:46:51,7.1S,75.9E,38.0,-28.1,0.1,-0.5,7.500000e+11,1.800
19,2025-02-22 10:26:08,28.1N,120.0E,46.7,-5.0,-11.1,-8.8,5.500000e+10,0.180
20,2025-02-22 00:16:50,6.9S,12.1E,35.0,NaN,NaN,NaN,3.500000e+10,0.120
21,2025-02-12 04:33:39,73.4N,49.3E,42.0,9.5,19.6,-1.9,4.000000e+10,0.130
22,2025-02-07 17:25:57,14.4N,58.0W,50.8,-6.1,15.6,11.1,2.400000e+10,0.086
23,2025-02-06 17:52:54,1.7S,130.0E,36.2,3.4,-16.2,-5.5,2.000000e+10,0.073
24,2025-02-02 16:30:50,17.7S,24.3E,40.0,NaN,NaN,NaN,4.000000e+10,0.130
25,2025-01-11 14:46:00,1.2S,55.3E,61.0,6.8,-11.2,-1.7,2.900000e+10,0.100
26,2025-01-10 21:11:07,47.2N,106.3E,34.6,-7.1,-8.0,-9.0,2.700000e+10,0.095
27,2024-12-28 04:45:12,57.7N,168.1W,33.7,4.3,16.3,-2.2,3.100000e+10,0.110
28,2024-12-20 17:52:01,14.3N,98.1W,32.6,2.1,12.3,-17.0,1.542000e+12,3.400
29,2024-12-01 08:50:16,42.7S,172.4W,35.9,17.0,13.9,-2.4,1.300000e+11,0.380

[Wikipedia](https://en.wikipedia.org/wiki/Missing_data) has a great entry on missing data, I've reproduced a section of that entry below. Missing data is divided into the following catagories:


**Missing completely at random**

*Values in a data set are missing completely at random (MCAR) if the events that lead to any particular data-item being missing are independent both of observable variables and of unobservable parameters of interest, and occur entirely at random. When data are MCAR, the analysis performed on the data is unbiased; however, data are rarely MCAR.*

*(In the case of MCAR, the missingness of data is unrelated to any study variable: thus, the participants with completely observed data are in effect a random sample of all the participants assigned a particular intervention. With MCAR, the random assignment of treatments is assumed to be preserved, but that is usually an unrealistically strong assumption in practice.*

**Missing at random**

*Missing at random (MAR) occurs when the missingness is not random, but where missingness can be fully accounted for by variables where there is complete information. Since MAR is an assumption that is impossible to verify statistically, we must rely on its substantive reasonableness. An example is that males are less likely to fill in a depression survey but this has nothing to do with their level of depression, after accounting for maleness. Depending on the analysis method, these data can still induce parameter bias in analyses due to the contingent emptiness of cells (male, very high depression may have zero entries). However, if the parameter is estimated with Full Information Maximum Likelihood, MAR will provide asymptotically unbiased estimates.*

**Missing not at random**

*Missing not at random (MNAR) (also known as nonignorable nonresponse) is data that is neither MAR nor MCAR (i.e. the value of the variable that's missing is related to the reason it's missing). To extend the previous example, this would occur if men failed to fill in a depression survey because of their level of depression.*

Take a look at the missing data in this csv file. What types of missing data are there? To answer this question, you'll probably need to seek out additional information. Here's one place to start: https://fireballs.ndc.nasa.gov/

The missing data is missing not at random. This is because the data missing is due to there not being cameras in specific locations.

How do you choose to deal with this missing data?

[This guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html) may be useful, but you are not obligated to use it.

(Your answer here)

Implement your solution to deal with missing data below.

In [19]:
#This is an interesting resource:
#https://towardsdatascience.com/data-cleaning-with-python-and-pandas-detecting-missing-values-3e9c6ebcf78b

new_data = data.interpolate()
new_data.head(30)

/tmp/ipykernel_9873/1733806113.py:4: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_data = data.interpolate()

,Peak Brightness Date/Time (UT),Latitude (deg.),Longitude (deg.),Altitude (km),vx,vy,vz,Total Radiated Energy (J),Calculated Total Impact Energy (kt)
0,2025-09-13 22:24:59,38.1S,64.8W,25.1,-17.400000,1.700000,3.60,1.670000e+11,0.480
1,2025-09-10 11:00:57,14.8S,142.4W,37.0,-10.500000,11.050000,1.80,2.800000e+10,0.098
2,2025-09-09 17:49:10,2.3S,39.5W,24.0,-3.600000,20.400000,0.00,1.530000e+11,0.440
3,2025-09-08 10:09:15,26.4N,42.2E,28.4,5.550000,3.700000,0.05,3.600000e+10,0.120
4,2025-08-19 14:08:48,30.9N,131.8E,27.5,14.700000,-13.000000,0.10,6.580000e+11,1.600
5,2025-07-11 01:48:33,6.6S,167.5W,28.0,13.400000,1.800000,-0.90,3.200000e+10,0.110
6,2025-06-26 16:24:57,33.4N,84.1W,32.6,14.800000,6.050000,0.35,1.700000e+11,0.480
7,2025-06-26 00:37:20,12.1N,103.6W,30.0,16.200000,10.300000,1.60,1.320000e+11,0.390
8,2025-06-21 20:55:14,61.3S,157.9E,56.3,14.200000,9.450000,-4.05,3.000000e+10,0.100
9,2025-05-31 23:06:33,21.1N,98.8W,47.3,12.200000,8.600000,-9.70,3.860000e+11,1.000
10,2025-04-28 15:01:15,45.1S,67.3E,31.4,1.333333,8.966667,-6.60,3.400000e+10,0.120
11,2025-04-21 09:27:34,29.1S,151.6E,41.0,-9.533333,9.333333,-3.50,2.300000e+10,0.082
12,2025-04-08 14:16:48,32.2S,10.4E,44.9,-20.400000,9.700000,-0.40,2.100000e+10,0.076
13,2025-03-29 08:12:43,49.3S,14.3E,21.6,-8.900000,-5.200000,6.80,5.900000e+10,0.190
14,2025-03-27 16:05:23,14.3N,111.5W,38.1,-7.300000,19.800000,-2.80,1.045000e+12,2.400
15,2025-03-24 05:51:43,70.4S,114.2E,21.5,-0.900000,-24.800000,13.40,4.900000e+10,0.160
16,2025-03-21 05:06:26,22.8S,123.5E,54.2,-3.750000,-3.050000,5.15,3.900000e+10,0.130
17,2025-03-18 17:48:32,1.5S,30.4W,27.0,-6.600000,18.700000,-3.10,1.100000e+11,0.330
18,2025-03-13 09:46:51,7.1S,75.9E,38.0,-28.100000,0.100000,-0.50,7.500000e+11,1.800
19,2025-02-22 10:26:08,28.1N,120.0E,46.7,-5.000000,-11.100000,-8.80,5.500000e+10,0.180
20,2025-02-22 00:16:50,6.9S,12.1E,35.0,2.250000,4.250000,-5.35,3.500000e+10,0.120
21,2025-02-12 04:33:39,73.4N,49.3E,42.0,9.500000,19.600000,-1.90,4.000000e+10,0.130
22,2025-02-07 17:25:57,14.4N,58.0W,50.8,-6.100000,15.600000,11.10,2.400000e+10,0.086
23,2025-02-06 17:52:54,1.7S,130.0E,36.2,3.400000,-16.200000,-5.50,2.000000e+10,0.073
24,2025-02-02 16:30:50,17.7S,24.3E,40.0,5.100000,-13.700000,-3.60,4.000000e+10,0.130
25,2025-01-11 14:46:00,1.2S,55.3E,61.0,6.800000,-11.200000,-1.70,2.900000e+10,0.100
26,2025-01-10 21:11:07,47.2N,106.3E,34.6,-7.100000,-8.000000,-9.00,2.700000e+10,0.095
27,2024-12-28 04:45:12,57.7N,168.1W,33.7,4.300000,16.300000,-2.20,3.100000e+10,0.110
28,2024-12-20 17:52:01,14.3N,98.1W,32.6,2.100000,12.300000,-17.00,1.542000e+12,3.400
29,2024-12-01 08:50:16,42.7S,172.4W,35.9,17.000000,13.900000,-2.40,1.300000e+11,0.380

Please spend some time interrogating the data. Just becuase it comes from a NASA website doesn't mean it is perfect!
Feel free to investigate your own questions. If no questions come to mind, here's things I was curious about.
1. Does the data seem to cover all longitudes equally?
2. Does the data seem to cover all latitudes equally?
3. Are there geographic biases against observing faint objects?
(I found [this](https://cmdlinetips.com/2018/02/how-to-subset-pandas-dataframe-based-on-values-of-a-column/) useful for answering this question.)